// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rvipdpzpeqbmdpavhojs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2aXBkcHpwZXFibWRwYXZob2pzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjU5OTIsImV4cCI6MjA2NTUwMTk5Mn0.kq-csmvMYb5shzVY30VxKHAwDQlyu0k7-vYGoylymG8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);